### ISSUE TITLE
split_dataset_per_batch fails when no labels provided

### ISSUE THREAD

**Issue by fteufel** [pengminshi/cFIT#3]
Hi, I just used `split_datasets_per_batch`, closely following the vignette:

```
batches =  split_dataset_by_batch(X=t(as.matrix(seurat_object@assays$RNA@counts)), 
                                    batch=seurat_object@meta.data$Batch)
```
This yields the following error:
```
Error in names(labels.list[[i]]) <- rownames(X.list[[i]]) :
  'names' attribute [1205] must be the same length as the vector [0]
```
By adding `labels=seurat_object@meta.data$CellLabel` to the function call, it works.

This appears to be due to the condition
```
if (!is.null(rownames(X.list[[i]]))) {
```
in `data_preprocessing_utils.R`. I believe there should also be a check whether `labels` is `NULL`.

**Comment by pengminshi** [comment]
Fixed, thanks for raising the issue!
