### ISSUE TITLE
Issues with upscaling 

### ISSUE THREAD

**Issue by Nusob888** [pengminshi/cFIT#4]
Hi, 
cFIT looks promising as an integration method. However, I have not been able to run it. 
Does the conversion to a full matrix have to be done? This is obviously a big issues for large datasets as the sparsity inflates hugely and R will quickly give a Cholmod error. 

Is there an alternative you have used for larger datasets?

Thanks in advance

**Comment by pengminshi** [comment]
Thanks for your interest. Currently, the code only supports the full matrix. I will update the code soon to allow for sparse matrix.

Thanks again for raising the issue.
